### ISSUE TITLE
Module not found cec2019comp100digit

### ISSUE THREAD

**Issue by ayhaidar** [dmolina/cec2019comp100digit#1]
Hi Daniel, 

I tried downloading cec2019comp100digit using pip:
`alihaidar$ pip install cec2019comp100digit==0.4` and `alihaidar$ pip install cec2019comp100digit==0.3`
It didn't work:
![screen shot 2018-12-21 at 6 54 23 pm](https://user-images.githubusercontent.com/45418179/50331326-5dc29080-0552-11e9-9589-060480b93c63.png)

I downloaded the zip file, and in the  cec2019comp100digit I tried: `python setup.py install `. I didn't work due to malloc:
`cec2019comp100digit/cec19_func.cpp:14:10: fatal error: 'malloc.h' file not found
#include <malloc.h>
         ^
1 error generated.`

I changed the line of code (number 14) in cec19_func.cpp to `#include <malloc/malloc.h>` and tried `python setup.py  install`, it worked. When trying to run: `from cec2019comp100digit import cec2019comp100digit`, it returned an error: `ImportError: No module named cec2019comp100digit`.

I checked again pip install cec2019comp100digit, it shows Requirement already satisfied. I checked the site-packages, I found only cec2019comp100digit-0.4-py2.7-macosx-10.7-x86_64.egg

Any recommendations please?

**Comment by dmolina** [comment]
Dear ayhaidar, 

Thanks you for your advice. I have updated the source code from last version, trying to solve the problem. 
Sorry, malloc.h was not standard as I though. I have change it to avoid the problem. 

Please, could you test it again? First, using pip, and if it is not working, with the github version. However, the pip should be working. 

Thanks again for your information.

**Comment by ayhaidar** [comment]
I can confirm that it is now working. Thanks very much for providing this wrapping tool.

**Comment by dmolina** [comment]
Your welcome. 

Just for knowing, the pip install was working in your computer, or it was the github code?

**Comment by ayhaidar** [comment]
It was the pip install.
